# privileged pod to adjust permissions on a pv
kind: Pod
apiVersion: v1
metadata:
  name: resolve-permissions-pod
spec:
  containers:
    - name: resolve-permissions-container
      image: busybox
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
      - mountPath: "/data"
        name: my-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: postgresql
